# Use the official MongoDB image as the base image
FROM mongo:latest

# Expose the default MongoDB port
EXPOSE 27017

# RUN apt-get update && apt-get install -y mongodb-client

# CMD ["mongod", "--bind_ip", "0.0.0.0"]

